name: Run Pytest and Update Result

on:
  schedule:
    - cron: '0 15 * * *'
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test with pytest
      run: |
        ls -al
        pytest >> test_result.txt

    - name: Commit files
      run: |
        git config --global user.email "godhkekf24@inha.edu"
        git config --global user.name "SmileJune"
        git add test_result.txt
        git commit -m "Update test results"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}

